# Generated by Django 3.2.5 on 2021-07-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.tuteur'),
        ),
    ]
