# Generated by Django 3.2.5 on 2021-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleveclasse',
            name='anneeScolaire',
        ),
        migrations.AddField(
            model_name='eleve',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='eleves', to='classes.AnneeClasse'),
        ),
        migrations.AlterField(
            model_name='eleveclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.anneeclasse'),
        ),
        migrations.DeleteModel(
            name='AnneeScolaire',
        ),
    ]
