# Generated by Django 3.2.5 on 2021-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='annees', to='classes.Classe'),
        ),
    ]
