# Generated by Django 3.2.5 on 2021-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_anneescolaire_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='indice',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
