# Generated by Django 3.2.5 on 2021-07-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eleves.personne')),
                ('salaire', models.IntegerField()),
                ('matiere', models.CharField(max_length=30)),
            ],
            bases=('eleves.personne',),
        ),
        migrations.CreateModel(
            name='ProfesseurClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.professeur')),
            ],
        ),
    ]
