# Generated by Django 3.2.5 on 2021-07-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_auto_20210719_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('dateDePaiement', models.DateField(auto_now=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('mois', models.CharField(blank=True, max_length=12, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleveclasse')),
                ('typeDePaiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.typedepaiement')),
            ],
        ),
    ]
