# Generated by Django 3.2.5 on 2021-07-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('dateDePaiement', models.DateField(auto_now=True)),
                ('numero', models.IntegerField(null=True)),
                ('mois', models.CharField(max_length=12, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleveclasse')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='anneeScolaire',
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='professeur',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='ProfesseurClasse',
        ),
        migrations.AddField(
            model_name='paiement',
            name='typeDePaiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.typedepaiement'),
        ),
    ]
