# Generated by Django 3.2.5 on 2021-07-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_auto_20210718_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mois',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
