# Generated by Django 3.2.5 on 2021-07-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eleves.personne')),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=30)),
                ('classes', models.ManyToManyField(blank=True, related_name='eleves', to='classes.AnneeClasse')),
            ],
            bases=('eleves.personne',),
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eleves.personne')),
                ('parent', models.BooleanField()),
            ],
            bases=('eleves.personne',),
        ),
        migrations.CreateModel(
            name='EleveClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.anneeclasse')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.tuteur'),
        ),
    ]
